app/models.py
from flask_sqlalchemy import SQLAlchemy
from  datetime import  datetime
db = SQLAlchemy()

class Categorey(db.Model):
    __tablename__= 'categorey'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    ##### db.relationship("ModelName", -----)
    posts = db.relationship('Post', backref='categorey', lazy=True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def get_all_categories(cls):
        return cls.query.all()


class Post(db.Model):
    __tablename__ = 'posts'
    id= db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String(100))
    body=db.Column(db.String(1000))
    image=db.Column(db.String(300))
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated = db.Column(db.DateTime, onupdate=datetime.utcnow)
    ############################### db.foreignkey(table_name.id)
    cat_id = db.Column(db.Integer, db.ForeignKey('categorey.id'), nullable= True)


    def __str__(self):
        return f"{self.name}"

    @classmethod
    def get_all_posts(cls):
        return cls.query.all()


    def delete_object(self):
        db.session.delete(self)
        db.session.commit()
        return True

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,FileField


class PostForm(FlaskForm):
    title = StringField('Title')
    body = StringField('Body')
    image = FileField('Image')


class CategoryForm(FlaskForm):
    categoryName = StringField('Category Name')

app/__init__.py
from flask import  Flask
from flask_migrate import Migrate
from  app.models import  db
from app.config import  projectConfig as AppConfig   # this dict
from app.posts.api.api_views import AllPosts,PostGetSpecificAndUpdateAndDelete
from flask_restful import Api

def create_app(config_name):
    app = Flask(__name__)
    current_config = AppConfig[config_name]  # class
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config.SQLALCHEMY_DATABASE_URI
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config # search in this class about class variable with this name
    app.config['SECRET_KEY'] = current_config.SECRET_KEY

    app.config.from_object(current_config)
    db.init_app(app)

    ## add migration
    migrate = Migrate(app, db,render_as_batch=True)

    ### add route
    # from app.students.views import testfunction,students_index, student_info, student_delete
    # from app.students.errors import page_not_found
    # from app.departments.views import department_index
    #
    #
    # app.add_url_rule('/test', view_func=testfunction)
    # app.register_error_handler(404, page_not_found)
    # app.add_url_rule('/students', view_func=students_index)
    # app.add_url_rule('/students/<id>', view_func=student_info)
    # app.add_url_rule('/students/<id>/delete', view_func=student_delete)

    #################### blueprints
    from app.categorey import categories_blueprint
    from app.posts import posts_blueprint
    # app.add_url_rule('/departments', view_func=department_index, endpoint='departments_all')
    app.register_blueprint(categories_blueprint)
    app.register_blueprint(posts_blueprint)

    api = Api(app)
    api.add_resource(AllPosts, '/api/posts')
    api.add_resource(PostGetSpecificAndUpdateAndDelete, '/api/posts/<int:id>')

    return  app

app/categorey/__init__.py
from flask import  Blueprint

categories_blueprint= Blueprint('categories', __name__, url_prefix='/categories')

from app.categorey import  views

app/categorey/views.py
from flask import render_template,request,redirect
from app.models import Categorey
from app.categorey import  categories_blueprint
from app.posts.forms import CategoryForm
from  app.models import  db

@categories_blueprint.route('/')
def department_index():
    categories = Categorey.get_all_categories()
    return render_template('categorey/index.html',categories=categories )

@categories_blueprint.route('/createcategorey', methods = ['POST','GET'],endpoint="createcategorey")
def addNewCategory():
    form = CategoryForm()
    if request.method == 'GET':
        return render_template("categorey/createcategorey.html",form=form)
    if request.method == 'POST':
        print(request.form)
        category = request.form['categoryName']
        record = Categorey(name=category)
        db.session.add(record)
        db.session.commit()
        return redirect('/categories')

app/posts/__init__.py
from flask import  Blueprint

posts_blueprint= Blueprint('posts', __name__, url_prefix='/')

from app.posts import views

app/posts/views.py
from app.models import Post
from flask import  render_template, redirect, url_for,request
from app.models import Post,Categorey
from  app.models import  db
from .forms import PostForm,CategoryForm


from app.posts import  posts_blueprint
from app.categorey import  categories_blueprint

@posts_blueprint.route('test')
def testfunction():
    return '<h1> Posts Index </h1>'


@posts_blueprint.route('')
def posts_index():
    posts = Post.get_all_posts()

    return render_template('Posts/index.html', posts=posts)


@posts_blueprint.route('/<int:id>')
def post_info(id):
    post = Post.query.get_or_404(id)
    return render_template('Posts/show.html',post=post)

@posts_blueprint.route('/createpost', methods = ['POST','GET'],endpoint="createpost")
def create_post():
    form = PostForm()
    if request.method == 'GET':
        return render_template("Posts/createpost.html", form=form, category=Categorey.query.all())
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        category = request.form['category']
        record = Post(title=title,
                      body=body,
                      cat_id=category)

        db.session.add(record)
        db.session.commit()
        return redirect('/')

@posts_blueprint.route('/editpost/<int:id>/', methods=('GET', 'POST'),endpoint="editpost")
def editpost(id):
    post=Post.query.get_or_404(id)
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        post.title=title
        post.body=body
        db.session.add(post)
        db.session.commit()
        return redirect('/')
    return render_template('Posts/UpdatePost.html',post=post)





@posts_blueprint.route('/<int:id>/delete', endpoint='delete')
def post_delete(id):
    post = Post.query.get_or_404(id)
    res =post.delete_object()
    if res :
        return redirect(url_for("posts.posts_index"))

app/templates/Posts/UpdatePost.html
{%  extends 'base.html' %}

{% block title %} Update Post {% endblock %}

    {% block content %}

<div class="container text-light">
    <form method="POST"  >
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Title</label>
          <input type="text" class="form-control" name="title" value="{{post.title}}" id="exampleInputEmail1">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail2" class="form-label">Body</label>
            <input type="text" class="form-control" name="body" value="{{post.body}}"  id="exampleInputEmail2">
          </div>

        <button type="submit" class="btn btn-outline-light w-25 mx-auto">Update</button>
      </form>
</div>
    {% endblock %}

app/templates/Posts/createpost.html
{%  extends 'base.html' %}

{% block title %} Add New Post {% endblock %}

    {% block content %}
<div class="container text-light">
  <form method="POST">
    {{form.csrf_token}}
<div class="mb-3">
<div class="form-label"> {{form.title.label}}  </div>
{{form.title(value=title, class='form-control')}}

</div>
<div class="mb-3">
<div class="form-label"> {{form.body.label}}  </div>
{{form.body( value=body, class='form-control')}}

</div>

    <div class="mb-3">



<div class="mb-3">
  <div class="form-label"> {{form.image.label}}  </div>
  {{form.image(value=image, class='form-control')}}

  </div>
<div class="mb-3 ">
  <label for="cat" class="form-label">Category</label>
<select name="category" class="form-control" id="cat">
  {% for cat in category %}
      <option value="{{cat.id}}">{{cat.name}}</option>
  {% endfor %}
</select></div>

  <button type="submit" class="btn btn-outline-light w-25 mx-auto">Add New Post</button>
</form>
</div>
    {% endblock %}

app/templates/Posts/index.html
{%extends 'base.html'%}

 {% block title  %}
        students page
 {% endblock %}
{% block content %}
    <div class="">
        <h2 class="text-info text-center mb-5 ">
        All Posts
    </h2>
   <div class=" w-50 m-auto " >
           {% for post in posts %}
       <a class="text-decoration-none my-3" href="{{ url_for("posts.post_info",id=post.id) }}">
            <div  class=" shadow-sm p-3 mb-5 bg-body-tertiary rounded position-relative ">
                <h3 class="text-primary">  {{post.title}}</h3>
                 <div class="position-absolute top-0 end-0  ">

                     <a href="{{ url_for("posts.delete",id=post.id) }}" class="btn btn-light rounded-circle" >X</a>

                 </div>
                  <img  class="img-fluid" src="{{ url_for('static', filename = 'images/pexels-eric-mufasa-1350789_6w5liBR.jpg') }}" alt="">

                <p class="text-secondary my-3 "> {{post.body}}</p>
                <p class="text-secondary my-3 "> categorey: {{post.categorey}}</p>

                <p class="text-secondary my-3 "> {{post.created}}</p>
                <div class="d-flex justify-content-end">
                    <a href="{{ url_for("posts.editpost",id=post.id) }}"  class="btn btn-dark">edit</a>
                </div>

            </div>
        </a>
    {% endfor %}
   </div>
    </div>
{% endblock %}

app/templates/Posts/show.html
{%extends 'base.html'%}

 {% block title  %}
        Posts page
 {% endblock %}
{% block content %}
    <div>
        <h1 class="text-info text-center my-5">
        POst details
    </h1>
            <div class=" shadow-sm p-3 mb-5 bg-body-tertiary rounded position-relative w-50  m-auto ">
                <h3 class="text-primary"> {{post.title}}</h3>
                 <div class="position-absolute top-0 end-0  ">
                     <a href="{{ url_for("posts.delete",id=post.id) }}" class="btn btn-light rounded-circle" >X</a>
                 </div>
                  <img  class="img-fluid" src="{{ url_for('static', filename = 'images/pexels-eric-mufasa-1350789_6w5liBR.jpg') }}" alt="">
                <p class="text-secondary my-3 shadow-sm bg-body-tertiary">{{post.body}}</p>
                <p class="text-secondary my-3 "> categorey: {{post.categorey}}</p>

            </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>
      {% block title  %}

      {% endblock %}

    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('posts.posts_index')}}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100 justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('posts.createpost')}}">Add Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('posts.posts_index')}}">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('categories.createcategorey')}}">Add Categorey</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('categories.department_index')}}">Categories</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
 {%  block content  %}

{%  endblock  %}
</div>


<footer>
  <div>copyrights ITI@2023</div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

app/templates/categorey/createcategorey.html
{%  extends 'base.html' %}

{% block title %} Add New Category {% endblock %}

    {% block content %}

<div class="container text-light">
    <form method="POST">
      {{form.csrf_token}}
      <div class="mb-3">
        <div class="form-label"> {{form.categoryName.label}}  </div>
        {{form.categoryName(value=categoryName, class='form-control')}}

        </div>
        <!-- <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Category Name</label>
          <input type="text" class="form-control" name="name" id="exampleInputEmail1">
        </div> -->

        <button type="submit" class="btn btn-outline-light w-25 mx-auto">Add New Category </button>
      </form>
</div>
    {% endblock %}

app/templates/categorey/index.html
{%extends 'base.html'%}







{% block title  %}
        Categories
 {% endblock title  %}

{% block content %}
    <div class="">
        <h2 class="text-info text-center mb-5 ">
        All Categories
    </h2>
   <div class=" w-50 m-auto " >
           {% for post in categories %}
            <div  class=" shadow-sm p-3 mb-5 bg-body-tertiary rounded position-relative ">
                <h3 class="text-primary">  {{post.name}}</h3>
            </div>
    {% endfor %}
   </div>
    </div>
{% endblock %}

app/templates/categorey/show.html
{% extends 'base.html'%}

{% block content %}
    <div>

        <h1>Categorey Profile</h1>

    </div>
{% endblock %}

app/templates/not_found_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>not found</title>
</head>
<body>
<div class="d-flex justify-content-center flex-column">
  <h2 class=" text-info text-center"> NOt Found</h2>

<a href={{url_for("home",name="michael")}}> Got to home </a>

  <img src="https://colorlib.com/wp/wp-content/uploads/sites/2/404-error-template-19.png">
</div>
</body>
</html>